version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - checkout
      - run: 
          name: 'Install Dependencies'
          command: yarn install 
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: 'Run Tests'
          command: yarn test
      - coveralls/upload

  deploy:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - checkout
      - run:
          name: 'Deploy to Production'
          command: |
            yarn global add vercel
            vercel --prod --confirm --token $VERCEL_TOKEN 

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main  # Runs on pushes to the main branch
      - deploy:
          requires:
            - build  # Deploys after a successful build
